config/routes.rb
Rails.application.routes.draw do

  get 'authenticate/login'
  post 'authenticate/login'
  get 'authenticate/logout'

  resources :assignment_grades
  resources :parents
  resources :students
  resources :teachers

end

app/models/assignment_grade.rb
class AssignmentGrade < ActiveRecord::Base
  belongs_to :student
end

app/controllers/assignment_grades_controller.rb
class AssignmentGradesController < ApplicationController
  before_action :authenticate
  before_action :set_assignment_grade, only: [:show, :edit, :update, :destroy]

  # GET /assignment_grades
  # GET /assignment_grades.json
  def index
    @assignment_grades = AssignmentGrade.all
  end

  # GET /assignment_grades/1
  # GET /assignment_grades/1.json
  def show
  end

  # GET /assignment_grades/new
  def new
    @assignment_grade = AssignmentGrade.new
  end

  # GET /assignment_grades/1/edit
  def edit
  end

  # POST /assignment_grades
  # POST /assignment_grades.json
  def create
    @assignment_grade = AssignmentGrade.new(assignment_grade_params)

    respond_to do |format|
      if @assignment_grade.save
        format.html { redirect_to @assignment_grade, notice: 'Assignment grade was successfully created.' }
        format.json { render :show, status: :created, location: @assignment_grade }
      else
        format.html { render :new }
        format.json { render json: @assignment_grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignment_grades/1
  # PATCH/PUT /assignment_grades/1.json
  def update
    respond_to do |format|
      if @assignment_grade.update(assignment_grade_params)
        format.html { redirect_to @assignment_grade, notice: 'Assignment grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment_grade }
      else
        format.html { render :edit }
        format.json { render json: @assignment_grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignment_grades/1
  # DELETE /assignment_grades/1.json
  def destroy
    @assignment_grade.destroy
    respond_to do |format|
      format.html { redirect_to assignment_grades_url, notice: 'Assignment grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment_grade
      @assignment_grade = AssignmentGrade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_grade_params
      params.require(:assignment_grade).permit(:assignment_name, :grade, :student_id)
    end
end

app/helpers/assignment_grades_helper.rb
module AssignmentGradesHelper
end

app/views/assignment_grades/_form.html.erb
<%= form_for(@assignment_grade) do |f| %>
  <% if @assignment_grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment_grade.errors.count, "error") %> prohibited this assignment_grade from being saved:</h2>

      <ul>
      <% @assignment_grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :assignment_name %><br>
    <%= f.text_field :assignment_name %>
  </div>
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.text_field :grade %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignment_grades/edit.html.erb
<h1>Editing Assignment Grade</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment_grade %> |
<%= link_to 'Back', assignment_grades_path %>

app/views/assignment_grades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Assignment Grades</h1>

<table>
  <thead>
    <tr>
      <th>Assignment name</th>
      <th>Grade</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assignment_grades.each do |assignment_grade| %>
      <tr>
        <td><%= assignment_grade.assignment_name %></td>
        <td><%= assignment_grade.grade %></td>
        <td><%= assignment_grade.student_id %></td>
        <td><%= link_to 'Show', assignment_grade %></td>
        <td><%= link_to 'Edit', edit_assignment_grade_path(assignment_grade) %></td>
        <td><%= link_to 'Destroy', assignment_grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assignment grade', new_assignment_grade_path %>

app/views/assignment_grades/new.html.erb
<h1>New Assignment Grade</h1>

<%= render 'form' %>

<%= link_to 'Back', assignment_grades_path %>

app/views/assignment_grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Assignment name:</strong>
  <%= @assignment_grade.assignment_name %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @assignment_grade.grade %>
</p>

<p>
  <strong>Student:</strong>
  <%= @assignment_grade.student_id %>
</p>

<%= link_to 'Edit', edit_assignment_grade_path(@assignment_grade) %> |
<%= link_to 'Back', assignment_grades_path %>